/**
 * VEXTONY REPOSITORY CONFIGURATION INFRASTRUCTURE
 * SOURCE PATH: `src/config/legal-trust-charter.ts`
 * [ARCHITECTURE LAYER: CENTRAL ISOLATED OPERATIONAL & LEGAL SHIELD CONFIG MATRIX]
 * [COMPLIANCE: NEXT.JS 14+ STATIC INVARIANT LEDGER • ZERO API TOKEN INGESTION OVERHEAD]
 * STATUS: 100% SECURE • NO RIBA PROVISIONS ENFORCED • DECOUPLED FROM PRODUCT VAULTS
 */

export interface SovereignLegalClause {
  id: string;
  clauseTitle: string;
  clauseContentSummary: string;
  operationalScope: "Global" | "Edge-Pool" | "Sovereign-Trust";
}

export const LEGAL_TRUST_CHARTER_REGISTRY: SovereignLegalClause[] = [
  { id: "LTC-1", clauseTitle: "The Invariant Cross-Border User Responsibility Covenant", clauseContentSummary: "ইউজার বা মেম্বাররা এই প্ল্যাটফর্মের কোনো ডাটা বা বাটন নিজের প্র্যাক্টিক্যাল লাইফে অ্যাকশন করার আগে সম্পূর্ণ নিজের দায়িত্বে করতে বাধ্য থাকবে। সিস্টেম বা প্ল্যাটফর্মের ওনার কোনো পার্সোনাল লায়াবিলিটি বহন করবে না।", operationalScope: "Global" },
  { id: "LTC-2", clauseTitle: "Decoupled Financial Settlement Indemnification Matrix", clauseContentSummary: "স্ট্রাইপ বা পেমেন্ট গেটওয়ের সমস্ত ট্রাঞ্জেকশন থার্ড-পার্টি কাস্টমার অথেন্টিকেশন প্রোটোকল দ্বারা সম্পূর্ণ সুরক্ষিত। ইউজার অ্যাকাউন্টের কোনো পাসওয়ার্ড মিসইউজ বা মিসম্যাচের জন্য সেন্ট্রাল অ্যাকাউন্ট ব্যালেন্স সম্পূর্ণ দায়মুক্ত থাকবে।", operationalScope: "Global" },
  { id: "LTC-3", clauseTitle: "Cryptographic Digital Asset Execution Risk Mitigation Shield", clauseContentSummary: "কোডের কোনো এপিআই run-time বা সফটওয়্যার মিডলওয়্যার ইউজার যদি তার লোকাল হোস্টে ডেপ্লয় করে, তবে তার লোকাল সার্ভারের কোনো ওভারহেড বা ব্যান্ডউইথ ল্যাগের জন্য আমাদের ক্লাউড বাউন্ডারি রেসপন্সিবল থাকবে না।", operationalScope: "Edge-Pool" },
  { id: "LTC-4", clauseTitle: "International Arbitrage Non-Jurisdictional Forum Inversion Protocol", clauseContentSummary: "প্ল্যাটফর্মের যেকোনো আইনি কন্ডিশন বা ফোরাম ভেরিфикации সম্পূর্ণ থার্ড-পার্টি স্বাধীন অফশোর মেরিটাইম কোডের আন্ডারে রিজলভ হবে, যা তোর মূল ডোমেইন বা পার্সোনাল বিজনেস সত্ত্বাকে চিরকাল স্পর্শের বাইরে রাখবে।", operationalScope: "Global" },
  { id: "LTC-5", clauseTitle: "Force Majeure Automated Network Disruption Failover Clause", clauseContentSummary: "গ্লোবাল ইন্টারনেট ক্লাউড ডাউন বা হোস্টিং প্রোভাইডারের ডাটা সেন্টার বাফারিং এররজনিত যেকোনো সাময়িক বিঘ্নে ইউজারের সার্ভিস হোল্ড হলে, সিস্টেম স্বয়ংক্রিয় ব্যাকআপ রুলসে শিফট হবে এবং কোনো ফিন্যান্সিয়াল ক্লেইম ভ্যালিড হবে না।", operationalScope: "Edge-Pool" },
  { id: "LTC-6", clauseTitle: "Ephemeral Intellectual Property Licensing User Limitation Boundary", clauseContentSummary: "ড্যাশবোর্ডের সব রিড-অনলি আর্টিকেল ও কোড স্ট্রাকচার শুধুমাত্র একক ইউজারের লার্নিং ও ক্যারিয়ার ইমপ্রুভমেন্টের লাইসেন্স গ্র্যান্ট করে। এটিকে পাইরেসি বা কমার্শিয়ালি রিসেল করা আইনত সম্পূর্ণ নিষিদ্ধ।", operationalScope: "Sovereign-Trust" },
  { id: "LTC-7", clauseTitle: "Continuous Third-Party Webhook Data Validation Integrity Protocol", clauseContentSummary: "কাস্টমার সেশনের সিকিউরিটি এনশিওর করতে সমস্ত আউটগোয়িং এপিআই এবং পেমেন্ট রিকোয়েস্ট ইনস্ট্যান্ট গেটকিপার দ্বারা অডিট হবে, যা তোর ওমেগা প্রজেক্টকে রিফান্ড বা充电ব্যাক ব্ল্যাকমেইলিং থেকে ১০০% সেফ রাখবে।", operationalScope: "Global" },
  { id: "LTC-8", clauseTitle: "Automated Account Session Eviction Security Safeguard Standard", clauseContentSummary: "একটি প্রিমিয়াম বা ফ্রি মেম্বারশিপ অ্যাকাউন্ট থেকে একই সাথে মাল্টিপল আইপি বা ব্রাউজারে সাইমালটেনিয়াস লগইন রিকোয়েস্ট ডিটেক্ট হলে, সিস্টেম অটো-লক ফায়ার করবে যা ফালতু অ্যাকাউন্ট শেয়ারিং চিরতরে বন্ধ রাখবে।", operationalScope: "Edge-Pool" },
  { id: "LTC-9", clauseTitle: "Zero-Malware Static Output Content Sanitization Verification", clauseContentSummary: "প্ল্যাটফর্ম থেকে ডেলিভারড প্রতিটি মেটা-ডাটা ফাইল এবং গাইডবুক ডাউনলোড রেন্ডার হওয়ার আগে এজ সিডিএন লেয়ারে স্ক্যান হবে, যা ইউজারের লোকাল ব্রাউজার সিকিউরিটিকে সর্বোচ্চ প্রটেকশন দেবে।", operationalScope: "Sovereign-Trust" },
  { id: "LTC-10", clauseTitle: "Ultimate Domain Invariant Operational Closure Sovereignty Rule", clauseContentSummary: "এই গ্লোবাল সংবিধানের প্রতিটি ধারা প্ল্যাটফর্মের যেকোনো বর্তমান ও ভবিষ্যৎ পণ্যের ফাইল, SERVICE বাটন এবং মেটা-ডাটা নোডের ওপর স্বয়ংক্রিয় অটোনোমাস বাউন্ডারি শিল্ড হিসেবে চিরকাল কার্যকর থাকবে।", operationalScope: "Sovereign-Trust" },
  { id: "LTC-11", clauseTitle: "Clear Fair-Value Non-Predatory Commerce Covenant", clauseContentSummary: "এই প্ল্যাটফর্মের কোনো সার্ভিসের পেছনে কোনো হিডেন চার্জ, ফালতু অতিরিক্ত ট্রাঞ্জেকশন ফি বা সুদী চক্রবৃদ্ধি ফি (Predatory Billing) থাকবে না। চেকআউট বাটন-এ ক্লিক করার আগেই ইউজার তার পেমেন্টের সুনির্দিষ্ট ভ্যালু পরিষ্কার দেখতে পাবে।", operationalScope: "Global" },
  { id: "LTC-12", clauseTitle: "Zero-Predatory Autonomous Billing Control Protection", clauseContentSummary: "কাস্টমারদের কোনো নোটিশ ছাড়া অটো-ডেবিট বা জোর করে সাবস্ক্রিপশন কিউতে লক করে রাখা হবে না। ড্যাশবোর্ডে ওয়ান-ক্লিক ক্যানসেলেশন বাটন থাকবে, যার মাধ্যমে ইউজার তার ওয়ালেট ও পেমেন্ট পাইপলাইনের ওপর সম্পূর্ণ স্বাধীন ও সার্বভৌম নিয়ন্ত্রণ নিজের হাতে রাখবে।", operationalScope: "Edge-Pool" },
  { id: "LTC-13", clauseTitle: "Proactive Telemetry Data Privacy & Transparency Charter", clauseContentSummary: "ইউজারদের ব্রাউজিং সেশন বা পার্সোনাল আইডেন্টিটি ডেটা কোনো কমার্শিয়ালি ট্র্যাকিং কোম্পানি বা থার্ড-পার্টি অ্যাড-নেটওয়ার্কের কাছে বিক্রি করা এক কোটি পার্সেন্ট নিষিদ্ধ। প্রতিটি সেশন কোয়ান্টাম-গ্রেড সিকিউরিটি কি দিয়ে এনক্রিপ্ট থাকবে।", operationalScope: "Global" },
  { id: "LTC-14", clauseTitle: "Decoupled Merchant Service SLA Downtime Safeguard", clauseContentSummary: "ব্যাকঅ্যান্ড এপিআই ওভারহেড বা হোস্টিং প্রোভাইডারের জ্যামের কারণে কোনো পেইড বাটন রান হতে লেট বা ল্যাগ করলে, SYSTEM অটোমেটিক ইউজার টোকেন সেভ জোনে হোল্ড করবে এবং ব্যাকঅ্যান্ড থেকে ১ মিলিসেকেন্ডে টিকেট জেনারেট করে সলিউশন করবে।", operationalScope: "Edge-Pool" },
  { id: "LTC-15", clauseTitle: "Invariant Value Protection & Fair Refund Framework", clauseContentSummary: "যদি কোনো টেকনিক্যাল বিল্ড এররের কারণে সিস্টেম কোনো পেইড সার্ভিসের ফাইনাল আউটপুট রেন্ডার করতে সম্পূর্ণ ব্যর্থ হয়, তবে আইনি ও नैतिक সততা অনুযায়ী পেমেন্ট ভেরিফিকেশন লুপ সাকসেসফুলি রি-অ্যালাইন বা রিফান্ড করার সুনির্দিষ্ট সচ্ছ মেকানিজম থাকবে।", operationalScope: "Global" },
  { id: "LTC-16", clauseTitle: "Truthful Content Metrics and Verification Assurance", clauseContentSummary: "প্ল্যাটফর্মের কোনো বাটন বা গাইডে কোনো মিথ্যা মার্কেটিং, ক্লিক-বেইট ইনফরমেশন বা এআই জেনারেটেড ভুয়া মনগড়া স্ক্র্যাপড ডেটা ঢুকিয়ে কাস্টমারকে ধোঁকা (Gharar) দেওয়া হবে না। প্রতিটি লগের পেছনে জেনুইন টেকনিক্যাল ভেরিফিকেশন ও ট্রুথ ফিল্টার থাকবে।", operationalScope: "Edge-Pool" },
  { id: "LTC-17", clauseTitle: "Multi-Tenant Workspace Fair-Use Limit Optimization", clauseContentSummary: "মাল্টি-টেন্যান্ট ড্যাশবোর্ডের মেইন কম্পিউটেশনাল বাউন্ডারি যেন কোনো ক্ষতিকারক বটের সিঙ্গেল অ্যাটাকে ক্র্যাশ না করে, তার জন্য প্রতিটি অ্যাকাউন্টের রিসোর্স লিমিট সুশৃঙ্খলভাবে ব্যালেন্সড থাকবে, যাতে সাধারণ কোনো ভালো ইউজার স্পিড ল্যাগ বা বাফারিং প্যারা না খায়।", operationalScope: "Global" },
  { id: "LTC-18", clauseTitle: "Transparent Platform Token Compute Ingestion Ledger", clauseContentSummary: "ইউজার তার ড্যাশবোর্ডে বসে লাইভ ট্র্যাকিং প্যানেলের মাধ্যমে দেখতে পাবে সে ব্যাকঅ্যান্ডের কোন কোন ডেটা নোড বা এপিআই-এর সাথে ইন্টারঅ্যাক্ট করছে। কোনো কিছু ব্যাকস্টেজ বা ছায়ার আড়ালে ইউজারের অজান্তে ট্র্যাকিং বা রান করা হবে না।", operationalScope: "Sovereign-Trust" },
  { id: "LTC-19", clauseTitle: "Non-Deceptive Subscription UI Transparency Standard", clauseContentSummary: "মেম্বারশিপ পাস বা বাটন পেমেন্ট নেওয়ার সময় কোনো ডার্ক প্যাটার্ন, পেজ স্ক্রলিং ট্রিকস বা ধোঁয়াশাপূর্ণ টেক্সট ব্যবহার করা সম্পূর্ণ নিষিদ্ধ। ব্যবসা চলবে কাঁচের মতো পরিষ্কার এবং ১ কোটি পার্সেন্ট জ্যান্ত সততার ওপেন পলিসিতে।", operationalScope: "Edge-Pool" },
  { id: "LTC-20", clauseTitle: "Pure Anti-Exploitation and Non-Speculative Commerce Core", clauseContentSummary: "এই প্ল্যাটফর্মের কোনো রিসোর্স, ডাটা বা গাইডবুক কোনো প্রকার জুয়া (Gambling), ফাটকাবাজি, বা ইন্টারনেটের কোনো ক্ষতিকারক জিরো-সাম গেমের (Zero-Sum Game) উদ্দেশ্যে ব্যবহার করা কঠোরভাবে নিষিদ্ধ। কন্টেন্ট ব্যবহার হবে শুধুমাত্র ক্যারিয়ার বিল্ডিং ও হালাল ক্যাশф্লো ইম্প্রুভমেন্টের জন্য।", operationalScope: "Sovereign-Trust" },
  { id: "LTC-21", clauseTitle: "Parasitic AI Autonomous Scraping & Data Extraction Intervention Treaty", clauseContentSummary: "ওপেনএআই (OpenAI), অ্যানথ্রোপিক (Anthropic) বা গুগলের কোনো চোর এআই বট বা অটোমেটেড ওয়েব-ক্রলার এই প্ল্যাটফর্মের রাজকীয় কন্টেন্ট ও ডেটাবেজ ফ্রিতে স্ক্র্যাপ বা চুরি করতে পারবে না। কোনো অবৈধ রিকোয়েস্ট ডিটেক্ট হওয়া মাত্রই লিগ্যাল রাইটস অনুযায়ী ব্যবস্থা নেওয়া হবে।", operationalScope: "Global" },
  { id: "LTC-22", clauseTitle: "Edge CDN Network Abuse Layer-7 Deflection Guard Standard", clauseContentSummary: "সাবডোমেইনের বাসাগুলোকে সুরক্ষিত রাখতে চব্বিশ ঘণ্টা স্বয়ংক্রিয় রেট-লিমিটিং ফায়ারওয়াল একটিভ থাকবে ভাই। কোনো ক্ষতিকারক বটনেট বা ফালতু এপিআই স্নাইপার লুপ হিট করলে, SYSTEM অটোমেটিক তার ট্রাফিক মেইন গেটের বাইরে ছুড়ে ফেলবে।", operationalScope: "Edge-Pool" },
  { id: "LTC-23", clauseTitle: "Cryptographic Sovereign Authentication Spoof Session Eviction", clauseContentSummary: "কুকি বা ব্রাউজার সেশনের প্রক্সি ম্যানিপুলেশন করে কোনো চোর হ্যাকার যদি প্রিমিয়াম বা বাটন তালা অবৈধভাবে খোলার ১ পিক্সেল চেষ্টা করে, ব্যাকঅ্যান্ড এজ-মিডলওয়্যার সাথে সাথে তার সেশন লাইভ ডিলিট করে অ্যাকাউন্ট চিরতরে সাসপেন্ড করে দেবে।", operationalScope: "Global" },
  { id: "LTC-24", clauseTitle: "Non-Hostile Application Algorithmic Reverse Engineering Prohibition", clauseContentSummary: "এই প্ল্যাটফর্মের ব্যাকঅ্যান্ডে থাকা কোনো টাইপস্ক্রিপ্ট সোর্স কোড বা অটোনোমাস মাইক্রো-SaaS এক্সিকিউটেবল স্ক্রিপ্টের ইন্টারনাল মেকানিজম রিভার্স-ইঞ্জিনিয়ারিং বা ডি-কম্পাইল করার চেষ্টা করা আইনত সম্পূর্ণ দণ্ডনীয়।", operationalScope: "Sovereign-Trust" },
  { id: "LTC-25", clauseTitle: "Multi-Cloud Failover Continuous Invariant Boundary Shield", clauseContentSummary: "গ্লোবাল ট্রাফিক ওভারলোডের কারণে মেইন সার্ভার ডাউন হলে ব্যাকআপ মিরর বা ক্লাউড নোডে ডেটা রিডিরেক্ট হলেও, এই লিগ্যাল সংবিধান এবং কাস্টমারের সমস্ত প্রাইভেসি রাইটস প্রতিটি সাবডোমেইনে সমানভাবে কার্যকর থাকবে।", operationalScope: "Edge-Pool" },
